version: '3.1'

# Run proxy server and Total.js Code
services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  code:
    container_name: code
    image: totalplatform/code
    volumes:
      - codedata:/databases
      - /your_working_path/:/www/www     # Edit development folder
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
    - VIRTUAL_HOST=code.localhost
    - VIRTUAL_PORT=8000
    - FOLDER_WWW=/your_working_path/     # Edit development folder
    - FOLDER_MODULES=/your_working_path/ # Edit node_modules folder

volumes:
  codedata:

networks:
  default:
    name: proxy